# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5846658d23744da8732d4cf05529fe9a00f7155105726a95ab9f9218c1b7857546412bbada332f5d38bb27cc6930948b9b00165c2ba2ea1bfedab4959bfb3cfa

test:
  secret_key_base: 03bd68be808d52720f32332c25ad2097c99016556e425a4cc6a80ce88395231640943fd48ce54bbdffb988919df6b8ea31f2d86ec0b0213d826431dacf599c88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
